# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d03f8f2b226d9e68f22f34dcacb2f58660aa310e41473cc934b95d83b460e937eb278ebe2626e5dbb962699fad919dbf9b9353b7c87989bde97e337baec43c20

test:
  secret_key_base: 95edb71d658f0eeb8d1fcc88bdf61cbf6c4857fb9278a359f0f8d5c8c559d86d5d42760be3f6d32571b60ed69ec471ebfadfa87acba7f582eac2ac82463e996a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
